import re
from typing import Dict

def merge_agent_outputs(plan: str, copy: str, code: str) -> Dict[str, str]:
    """
    Aggregator - Merges outputs from all 3 agents into a cohesive result.
    
    Args:
        plan: Output from planner agent
        copy: Output from copywriter agent
        code: Output from code generator agent
    
    Returns:
        Dictionary with merged results and improvements
    """
    
    # Extract improvements from plan
    improvements = extract_improvements(plan)
    
    # Create final merged output
    merged = {
        "plan": plan,
        "copywriting": copy,
        "code": code,
        "final_code": enhance_code_with_copy(code, copy),
        "improvements": improvements,
        "summary": generate_summary(plan, copy, code)
    }
    
    return merged


def extract_improvements(plan: str) -> list:
    """Extract improvement suggestions from the plan."""
    improvements = []
    
    # Look for common improvement patterns
    patterns = [
        r"recommend[s]?:?\s*(.+?)(?:\n|$)",
        r"suggest[s]?:?\s*(.+?)(?:\n|$)",
        r"consider:?\s*(.+?)(?:\n|$)",
        r"improvement:?\s*(.+?)(?:\n|$)"
    ]
    
    for pattern in patterns:
        matches = re.findall(pattern, plan, re.IGNORECASE)
        improvements.extend(matches)
    
    # Add default improvements
    if not improvements:
        improvements = [
            "Add smooth scroll animations",
            "Implement responsive design breakpoints",
            "Include accessibility features (ARIA labels)",
            "Add loading states for better UX"
        ]
    
    return improvements[:5]  # Limit to top 5


def enhance_code_with_copy(code: str, copy: str) -> str:
    """
    Enhance the generated code by ensuring it uses the copywriter's text.
    This is a simple version - in production, you'd use more sophisticated merging.
    """
    # For now, return the code as-is
    # In a real implementation, you'd parse the code and inject the copy
    enhanced = f"""// Generated by Vibe-Coding Multi-Agent System
// This code incorporates insights from:
// - Planner Agent (Architecture)
// - Copywriter Agent (Marketing Copy)
// - Code Generator Agent (Implementation)

{code}

/*
MARKETING COPY TO USE:
{copy}
*/
"""
    return enhanced


def generate_summary(plan: str, copy: str, code: str) -> str:
    """Generate a summary of what was created."""
    
    # Count components in code
    component_count = code.count("const ") + code.count("function ")
    
    summary = f"""✅ Multi-Agent Generation Complete

🧠 Planner Agent: Created architecture and UX strategy
✍️ Copywriter Agent: Generated premium marketing copy
⚡ Code Agent: Built {component_count}+ React components

The final output includes:
- Complete React + TypeScript codebase
- Professional component structure
- Premium marketing copy integrated
- Extra improvements and recommendations
"""
    
    return summary
